spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: 123
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cacheNames:
      - titleAuthor
      - categories
    caches:
      titleAuthor:
        expiry: 10m
      categories:
        expiry: 10m
server:
  port: 9090